### ISSUE TITLE
Cannot find propertiesOfInterest.json file

### ISSUE THREAD

**Issue by dhruvghulati-zz** [uclmr/simpleNumericalFactChecker#1]
In `numberExtraction.py`, in `_main_`you refer to:

```
propertiesOfInterest = {}
    with open(dirName + "../propertiesOfInterest.json") as props:
        propertiesOfInterest = json.loads(props.read())
```

However I cannot find this file. Should this step of generating that JSON file be within the first step, `FreeBaseDownload.py`? Secondly, in `FreeBaseDownload.py` you refer to:

`api_key =  open("/cs/research/intelsys/home1/avlachos/freebaseApiKey").read()`, it may be worth inserting a generic API key to use for this so that others can reuse the code?

**Comment by andreasvlachos** [comment]
Yes, the `propertiesOfInterest.json` file would have been generated from the first step, I added it now. Not sure what you mean with putting a generic API key, I only have my personal one, but I wouldn't want to put it in a public repo. However, note that Freebase is now being phased out: https://plus.google.com/109936836907132434202/posts/3aYFVNf92A1

Thus I would not spend time trying to get data out of it, as it is not being updated. Better to work with the data I have there already to save time and effort. If we want to obtain different/newer data, the best source I could find is the World Bank: http://databank.worldbank.org/data/home.aspx

But as said, you might want to look at familiarising yourself with the code using the existing data first.
