### ISSUE TITLE
The claims identified and annotated manually are attached to our submission...

### ISSUE THREAD

**Issue by dhruvghulati-zz** [uclmr/simpleNumericalFactChecker#12]
Have you done a qualitative evaluation of high MAPE sentences that you found just out of interest?

What is the significance of a high MAPE sentence that has then been labelled as actually being a claim? Is there a relationship you found between high MAPE sentences in your labelled claims vs. them being actually labelled as claims or not?

**Comment by andreasvlachos** [comment]
I have done a bit; high MAPE usually was either due to wrongly identified claim by my algorithm (e.g. "population of 80% muslim"), or due to the claim being out of date (using old census data). Note that all the claims mentioned in the excel sheets were labeled by the algorithm as claims independently of MAPE.

**Comment by dhruvghulati-zz** [comment]
Yes, from what I understand they are labelled as claims if they contain a pattern which you identified in your previous steps as part of the group of patterns for that statistical region. You mention in the paper that each pattern for each statistical property is ranked in terms of how well it does in reducing MAPE for a particular property and set of region-value pairs against the KB, is this rank used anywhere or stored anywhere in the Excel files? Or have I misunderstood.

**Comment by andreasvlachos** [comment]
No, the scores used to rank the patterns are not used once their selection is done and thus they do not appear in the excel files. You could extract them from the code, but I am not sure how useful they will be.
