### ISSUE TITLE
What were the steps to ignore and filter properties from propertiesOfInterest.json into featuresKept.json?

### ISSUE THREAD

**Issue by dhruvghulati-zz** [uclmr/simpleNumericalFactChecker#13]
Was this related to some analysis of the data within those properties within Freebase? 

_Requiring each region-pattern combination to have appeared at least twice and its values to have stan￼dard deviation less than 0.1._

This seems to relate to discarding training instances, not properties altogether.

**Comment by andreasvlachos** [comment]
This statement is related to the text patterns only, which was meant to help avoid uninformative patterns such as "COUNTRY is NUMBER"; for each country the numbers found with it in this pattern would be about all sorts of things, and thus have a very high deviation. The requirement for each region-pattern combination to have appeared twice is to enable us to do this check.
