### ISSUE TITLE
Retraining and running `factChecker.py` on a set of test instances

### ISSUE THREAD

**Issue by dhruvghulati-zz** [uclmr/simpleNumericalFactChecker#16]
The patterns based approach requires training on a set of tokens and dependencies, extracting patterns for each property, and then running again on some test instances to output sentences that have patterns corresponding to that property that your model has pre-selected. Then you evaluate manually via annotation.

I have a set of pre-labelled sentences, and want to effectively directly run the `factChecker` on only these sentences after having trained the model. I want to output, for these sentences, the property that the model predicts given its set of sentences.

How can I adapt the code to do this?

**Comment by andreasvlachos** [comment]
You can use the algorithm to learn a model per property (i.e. select patterns for each property). Then you can run it on any sentences presented in the json file format expected in this [line](https://github.com/uclmr/simpleNumericalFactChecker/blob/master/src/main/factChecker.py#L111) and it will decide whether a particular property is mentioned in the sentence or not.

Not sure what do you mean by "adapt", I think you can reuse the code for training but you will probably need to write the code to load the sentences and test them for each property.

**Comment by dhruvghulati-zz** [comment]
OK. If I have additional 750 test sentences I see that I need to retrain the full model pipeline including these 750 in the training. This is because I am guessing the `c` parameters also per property will change from the table provided in your README. The training format in your file is in[ textMatrix](https://github.com/uclmr/simpleNumericalFactChecker/blob/6a3fbad784282a03dfbf31388bb2ff8426ba1ddb/src/main/factChecker.py#L40), which comes from `theMatrixExtend120TokenFiltered_2_2_0.1_0.5_fixed2.json` and looks like:

```
{"LOCATION_SLOT,\",\",\"suite\",\"NUMBER\",\",\",\"LOCATION\",\",\",\"LOCATION\",NUMBER_SLOT": {"Pennsylvania Avenue NW": 20006.0, "N.W.": 20016.571428571428}, "LOCATION_SLOT~-prep_to+gone~nsubj+NUMBER_SLOT": {"Chad": 13000.0, "South Africa": 3000000.0}, "LOCATION_SLOT~-prep_of+balance~-nsubj+*extend*%~dep+NUMBER_SLOT": {"Saint Vincent and the Grenadines": -31.1, "Saint Kitts and Nevis": -9.67},
```

Then you load in each file in the [JSON file directory](https://github.com/uclmr/simpleNumericalFactChecker/blob/6a3fbad784282a03dfbf31388bb2ff8426ba1ddb/src/main/factChecker.py#L111) and then calculate the MAPEs. I am guessing I have to add a new JSON file to that directory? These files have to be in the format:

```
[{“tokens":[{"word":"Ã","lemma":"ã","pos":"CD","ner":"MONEY"},{"word":"cents","lemma":"cent","pos":"NNS","ner":"MONEY"},{"word":"Â","lemma":"â","pos":"NN","ner":"O"},{"word":"Â","lemma":"â","pos":"NN","ner":"O"},{"word":"¡","lemma":"¡","pos":"CD","ner":"NUMBER"},
```

My sentence file looks like:

```
[
    {
        "claim": 0, 
        "property": "/location/statistical_region/not_about_economic_statistics", 
        "parsedSentence": "’ä LOCATION_SLOT NUMBER_SLOT %"
    }, 
    {
        "claim": 1, 
        "property": "/location/statistical_region/population", 
        "parsedSentence": "It 's predicted that LOCATION_SLOT 's population will shrink to 3.1 million by 2050 , after reaching its peak of NUMBER_SLOT in 1991 ."
    }, 
```

So I do not have the tokens/lemma/pos for each parsed sentence. Nor do I have the dependency paths, nor do I retain the location-value pair specifically for that sentence (although I can definitely backtrack and obtain these as I do have a record for each parsed sentence, so adding entries to `textMatrix` is achievable). 

Obtaining the tokens/lemma/pos is a lot harder and would mean re-parsing each sentence in the case of adding the JSON file to the JSON directory, obtaining the list of `tokens` needed to produce each parsed sentence in my labels?

The file which kept record of the parsed sentences I sent out looks like this (as you can see I never stored the tokens to generate each parsed sentence - but I could?)

```
{
        "dense": false, 
        "sentence": "# 1 China : GDP at USD 24.6 trillion", 
        "depPath": [
            [
                "LOCATION_SLOT~-appos", 
                "MONEY~dep"
            ], 
            [
                "MONEY~dep", 
                "gdp~prep_at"
            ], 
            [
                "gdp~prep_at", 
                "MONEY~num"
            ], 
            [
                "MONEY~num", 
                "NUMBER_SLOT"
            ]
        ], 
        "parsedSentence": "# 1 LOCATION_SLOT : GDP at USD NUMBER_SLOT", 
        "slotSentence": "# NUMBER_SLOT LOCATION_SLOT : GDP at USD NUMBER_SLOT", 
        "location-value-pair": {
            "China": 24600000000000.0
        }
    }, 
    {
        "dense": false, 
        "sentence": "# 1 The American Society of Civil Engineers has given America\u00c3 cents \u00c2 $ \u00c2 s crumbling infrastructure an overall grade of D. # 2 There are simply not enough roads in the United States today .", 
        "depPath": [
            [
                "LOCATION_SLOT~-nn", 
                "DATE~-prep_in"
            ], 
            [
                "DATE~-prep_in", 
                "roads~-nsubj"
            ], 
            [
                "roads~-nsubj", 
                "are~-rcmod"
            ], 
            [
                "are~-rcmod", 
                "d.~amod"
            ], 
            [
                "d.~amod", 
                "NUMBER_SLOT"
            ]
        ], 
        "parsedSentence": "# 1 The American Society of Civil Engineers has given America\u00c3 cents \u00c2 $ \u00c2 s crumbling infrastructure an overall grade of D. # NUMBER_SLOT There are simply not enough roads in the LOCATION_SLOT today .", 
        "slotSentence": "# NUMBER_SLOT The American Society of Civil Engineers has given America\u00c3 cents \u00c2 $ \u00c2 s crumbling infrastructure an overall grade of D. # NUMBER_SLOT There are simply not enough roads in the LOCATION_SLOT today .", 
        "location-value-pair": {
            "United States": 2.0
        }
    }, 
```

**Comment by andreasvlachos** [comment]
Yes, you need to give parsed sentences as input. Given that all the sentences were parsed, this shouldn't be a problem.

**Comment by dhruvghulati-zz** [comment]
OK yes I can rerun to store the original dependencies from each sentence, should have done so from the start.

I just realised I might have been massively overcomplicating this. Since the annotated 750 sentences in question come from the same overall pool as `theMatrixExtend120TokenFiltered_2_2_0.1_0.5_fixed2.json`, it means your model is already trained on being able to pick out these 750 annotated sentences. In fact, perhaps all I actually need to do is get the 750 annotated sentences and see if they exist anywhere in the labeled claims files (i.e. were identified as claims about specific properties?).

The other potential tweaking aspect I can think of is that your model was generating sentences where all the location-value pairs for a sentence were in each instance, whereas I took combinations of location-value pairs `e.g. sentence 1: The population of LOCATION is NUMBER, but India's unemployment is 12m, sentence 2: the population of Germany is NUMBER, but LOCATION's unemployment is 12m.`. Do I need to somehow adjust the `factChecker.py` retraining to account for this multiplication in the number of training instances (these would be counted as separate patterns I guess)?

**Comment by dhruvghulati-zz** [comment]
Hi @andreasvlachos , does this mean I don't need to retrain? Given your model takes a pool of both training and test data, and spits out the data to be tested, shouldn't it already pick out the 750 sentences I annotated which were taken from the original pool of sentences anyways as claims? The only other thing I can think of to validate the need for training is that on my model, I train on 15k of the 150k sentences, and test on your 7092 claims. Perhaps I should just be now retraining your model on the same 15k + 7092 original claims + 750 added claims and seeing what pops out?

**Comment by andreasvlachos** [comment]
factChecker trains itself using unlabelled sentences and a knowledge base. Given that the sentences used in training are unlabelled, it makes sense to use as many as possible. As far as I can tell, you want to train it on labeled sentences, which is not how the algorithm operates and beyond the scope of this github repo. As explained above, you can test factChecker on new sentences as long as they are parsed in the json format expected. If the sentences are among the ones I provide with the code, then you have them parsed already.

**Comment by dhruvghulati-zz** [comment]
No, I don't want to train on labeled sentences. Neither are the 750 sentences I labeled new, they were originally from the same mainMatrix produced from `buildMatrix`. What I am saying is that most of those randomly chosen sentences should have been identified as claims in the first place and be also among the 7092 claims identified by the paper - am I right?

The only other thing I was thinking of doing was to ensure that `buildMatrix` is not training/building a matrix from any of the newly labeled 750 sentences/patterns i.e. it skips these sentences when creating the overall pattern file. Thus new c parameters could be created and one could reevaluate the algorithm, and see if the new run picks out the 750? Else I could do nothing and just go for the first approach.

**Comment by andreasvlachos** [comment]
I am not sure I can answer to this question:

>  most of those randomly chosen sentences should have been identified as claims in the first place and be also among the 7092 claims identified by the paper  - am I right?

It depends on how you did the random selection and what you mean by "most". If you chose randomly among those in the 7092 claims, then all of them were identified. Otherwise, given that you have the 7092 claims extracted in the labeled_claims directory, you should be able to find how many of them were.

You can use `buildMatrix.py` to build a new matrix excluding any sentences you don't want to use, you just need to modify the files in the directory passed as argument [here](https://github.com/uclmr/simpleNumericalFactChecker/blob/master/src/main/buildMatrix.py#L290) to exclude them. 

Finally, just to clarify this point (just in case there is a misunderstanding): the notions of pattern and sentence are not interchangeable in my code: a pattern (between an entity and a number) can be found in many sentences, and a sentence can contain many such patterns.

**Comment by dhruvghulati-zz** [comment]
@andreasvlachos Just to clarify this, I have built a new matrix, and passing into `factChecker.py` which is great, but do I also need to filter the sentences that are passed into `factChecker.py` to not go through certain files in the JSON directory too? Per [this section](https://github.com/uclmr/simpleNumericalFactChecker/blob/6a3fbad784282a03dfbf31388bb2ff8426ba1ddb/src/main/factChecker.py#L110-L111).
