### ISSUE TITLE
Linking sentences to original token and dependency set representing sentence

### ISSUE THREAD

**Issue by dhruvghulati-zz** [uclmr/simpleNumericalFactChecker#2]
I see from the [final](https://github.com/uclmr/simpleNumericalFactChecker/blob/9e75b20045043936cc7cd201687f496a922582a3/src/main/buildMatrix.py#L391-L395) lines that I can link each pattern observed to a set of EV pairs and the original sentence the pattern came from. However, how do I also link each pattern observed to the tokens and dependencies originally observed from each HTML JSON we obtained after step 6, and also what is in `theMatrixExtend120TokenFiltered_2_2_0.1_0.5_fixed2.json`?

e.g. `LOCATION_SLOT~-appos+*extend*putting~-prep_after+LOCATION~dep+PERCENT~number+NUMBER_SLOT` could be linked to:
- `"According to the most recent available data from the World Bank , Zambia\u00c3 cents \u00c2 $ \u00c2 s population growth rate in 2012 was at 3.2 % putting it in eighth position worldwide after Oman -LRB- 9.1 % -RRB- , Qatar -LRB- 7.1 % -RRB- , South Sudan -LRB- 4.3 % -RRB- , Kuwait -LRB- 3.9 % -RRB- , Niger -LRB- 3.8 % -RRB- , Uganda -LRB- 3.4 % -RRB- and Eritrea -LRB- 3.3 % -RRB- .".....`(6 instances of these sentences for each EV pair found in `mainMatrix.json_sentences`
- `"Eritrea": [
          9.1
      ],
      "Kuwait": [
          9.1
      ],
      "Niger": [
          9.1
      ],
      "Qatar": [
          9.1
      ],
      "South Sudan": [
          9.1
      ],
      "Uganda": [
          9.1
      ]` , which are the EV pairs found in `mainMatrix.json`
- What is missing is linking the above to the patterns and values we see in `theMatrixExtend120TokenFiltered_2_2_0.1_0.5_fixed2.json`. However, I found just from searching that I couldn't find any patterns that were in `mainMatrix.json_sentences` and `mainMatrix.json` that were also in `theMatrixExtend120TokenFiltered_2_2_0.1_0.5_fixed2.json` to then perhaps find EV pairs from this latter file, as example `"LOCATION_SLOT,\"MONEY\",\"MONEY\",\"-lrb-\",NUMBER_SLOT,\"people\",\"-rrb-\",\"NUMBER\"": {
      "Brazil": 191000000.0,
      "France": 65800000.0,
      "Italy": 60600000.0,
      "Mexico": 112000000.0
  },` as an example of a pattern (here obviously a non-matching pattern to what we want).
- The ideal would be to also retain the tokens and dependencies for the original sentence e.g. `"dependencies": [
          {
              "dep": 0,
              "head": 1,
              "label": "nn"
          }
      ],
      "tokens": [
          {
              "lemma": "World",
              "ner": "O",
              "pos": "NNP",
              "word": "World"
          },
          {
              "lemma": "fact",
              "ner": "O",
              "pos": "NNS",
              "word": "Facts"
          }
      ]
  },`, noting there may be multiple token/dependency pairs comprising a single sentence.

In general why this is useful is because if I can I rebuild the original text from the HTML web page JSONs you originally generated, and also have the tokens and dependencies, I could extend the work into for example LSTMs where I might need the sentences before and after a particular sentence? 

So overall `HTML JSON Full Text > FileName of HTML Web Page JSON > Sentences > Tokens/Dependencies > Patterns > Actual Entity, Region Value from text observed > Predicted Entity, Region, Value from MAPE algorithm > Freebase Entity, Region, Value` would be the goal,

**Comment by andreasvlachos** [comment]
The original sentence is actually reconstructed from the parsed sentence in
these lines:
https://github.com/uclmr/simpleNumericalFactChecker/blob/9e75b20045043936cc7cd201687f496a922582a3/src/main/buildMatrix.py#L330-L333

In them, the misleadingly named variable "sample" is set to the
concatenation of the words in the sentence using the sentence["tokens"].
You can access the dependencies for the sentence via sentence["dependencies"
]. See the lines here
https://github.com/uclmr/simpleNumericalFactChecker/blob/9e75b20045043936cc7cd201687f496a922582a3/src/main/buildMatrix.py#L118-L123
for an example.

On 9 June 2016 at 16:31, Dhruv Ghulati notifications@github.com wrote:

> I see from the final
> https://github.com/uclmr/simpleNumericalFactChecker/blob/9e75b20045043936cc7cd201687f496a922582a3/src/main/buildMatrix.py#L391-L395
> lines that I can link each pattern observed to a set of EV pairs and the
> original sentence the pattern came from. However, how do I also link each
> pattern observed to the tokens and dependencies originally observed from
> each HTML JSON we obtained after step 6?
> 
> e.g.
> LOCATION_SLOT~-appos+_extend_putting~-prep_after+LOCATION~dep+PERCENT~number+NUMBER_SLOT
> could be linked to:
> - "According to the most recent available data from the World Bank ,
>   Zambia\u00c3 cents \u00c2 $ \u00c2 s population growth rate in 2012 was at
>   3.2 % putting it in eighth position worldwide after Oman -LRB- 9.1 % -RRB-
>   , Qatar -LRB- 7.1 % -RRB- , South Sudan -LRB- 4.3 % -RRB- , Kuwait -LRB-
>   3.9 % -RRB- , Niger -LRB- 3.8 % -RRB- , Uganda -LRB- 3.4 % -RRB- and
>   Eritrea -LRB- 3.3 % -RRB- .".....(4 instances of these sentences for each
>   EV pair found in mainMatrix.json_sentences
> - "Eritrea": [ 9.1 ], "Kuwait": [ 9.1 ], "Niger": [ 9.1 ], "Qatar": [
>   9.1 ], "South Sudan": [ 9.1 ], "Uganda": [ 9.1 ] , which are the EV
>   pairs found in mainMatrix.json
> - What is missing is linking the above to the patterns and values we
>   see in theMatrixExtend120TokenFiltered_2_2_0.1_0.5_fixed2.json.
>   However, I found just from searching that I couldn't find any patterns that
>   were in mainMatrix.json_sentences and mainMatrix.json that were also in
>   theMatrixExtend120TokenFiltered_2_2_0.1_0.5_fixed2.json to then
>   perhaps find EV pairs from this latter file, as example "LOCATION_SLOT,\"MONEY\",\"MONEY\",\"-lrb-\",NUMBER_SLOT,\"people\",\"-rrb-\",\"NUMBER\"":
>   { "Brazil": 191000000.0, "France": 65800000.0, "Italy": 60600000.0,
>   "Mexico": 112000000.0 }, as an example of a pattern (here obviously a
>   non-matching pattern to what we want).
> - The ideal would be to also retain the tokens and dependencies for
>   the original sentence e.g. "dependencies": [ { "dep": 0, "head": 1,
>   "label": "nn" } ], "tokens": [ { "lemma": "World", "ner": "O", "pos":
>   "NNP", "word": "World" }, { "lemma": "fact", "ner": "O", "pos": "NNS",
>   "word": "Facts" } ] },, noting there may be multiple token/dependency
>   pairs comprising a single sentence.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/uclmr/simpleNumericalFactChecker/issues/2, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABbUhSY0l-mg0tCkKwx-1Lo9UvkrxdJqks5qKDHZgaJpZM4IyGlk
> .

## 

Andreas Vlachos
Lecturer
University of Sheffield

**Comment by dhruvghulati-zz** [comment]
This makes sense! I have tweaked your code to be able to obtain all the `samples` and create a dictionary `sentences2locations2values`, replacing the sentences with the LOCATION and NUMBER slots you produced using your code. An example of part of the output I can get to which is wrong is:

`"The LOCATION_SLOT LOCATION_SLOT in 1600 had NUMBER_SLOT NUMBER_SLOT ; in 1650 , NUMBER_SLOT NUMBER_SLOT .": {"Spanish Netherlands": [1500000.0]},`

However, using the tokenIDs, I am finding it difficult to account for this type of error as above, where the slot produced should be:

`The LOCATION_SLOT in 1600 had NUMBER_SLOT ; in 1650 , NUMBER_SLOT`

Here is the printed debugging I produce:

```
Value extracted is:  1500000.0
Value extracted is:  1900000.0
Value extracted is:  1500000.0
Value extracted is:  1900000.0
Location extracted is:  Spanish
Location extracted is:  Netherlands
Original sentence is :  The Spanish Netherlands in 1600 had 1.5 million ; in 1650 , 1.9 million .
Location token IDs are:  (1, 2)
Number token IDs are:  (12, 13)
Sample tokens are:  [u'The', u'Spanish', u'Netherlands', u'in', u'1600', u'had', u'1.5', u'million', u';', u'in', u'1650', u',', u'1.9', u'million', u'.']
New sample is:  The LOCATION_SLOT LOCATION_SLOT in 1600 had 1.5 million ; in 1650 , NUMBER_SLOT NUMBER_SLOT .
Location token IDs are:  (1, 2)
Number token IDs are:  (6, 7)
Sample tokens are:  [u'The', u'LOCATION_SLOT', u'LOCATION_SLOT', u'in', u'1600', u'had', u'1.5', u'million', u';', u'in', u'1650', u',', u'NUMBER_SLOT', u'NUMBER_SLOT', u'.']
New sample is:  The LOCATION_SLOT LOCATION_SLOT in 1600 had NUMBER_SLOT NUMBER_SLOT ; in 1650 , NUMBER_SLOT NUMBER_SLOT .
```

 Repo is [here](https://github.com/dhruvghulati/ClaimDetection/blob/efd422ff6bca7a95345874fe280dd86bba9ef84a/src/main/sentenceSlots.py#L343-L359) you should have access.

Given what you know of the code and the tokenID issues like above that exist, what is the best way of achieving what I need? Is the method I use not sophisticated enough? Is the splitting into the tokens as above matching how you did things?

**Comment by andreasvlachos** [comment]
Actually I don't agree that this:

`The LOCATION_SLOT in 1600 had NUMBER_SLOT ; in 1650 , NUMBER_SLOT`

should be the output. Each claim must identify a single location slot and a single number slot. In other words what is the claim in your example above? That the Spanish Netherland have two populations?  Given than we are ignoring the time (which is a shortcoming, but let's not address it at this point), the claims can have only one location slot and one number slot. The task you are labelling data for is whether a sentence contains the claim that the location_slot's population is number_slot, or not.

Does this make sense?

**Comment by dhruvghulati-zz** [comment]
I understand that you need to identify sentences with one location slot and one number slot, because that is the structure of the claims you can fact check from Freebase as this is the structure the Freebase data is in. Also, using your pattern based approach, you are initially extracting only patterns in between one location slot and one number slot, and not patterns with multiple location and number slots if I am not mistaken.

As some background, my methodology I am trying to achieve is that given a sentence that has identified slots of NUMBER and LOCATION, and known location-value pairs, can I estimate the statistical property from Freebase closest to this e.g. if I find England, and 60m, I can associate the sentence-region-value triple with "population" with a MAPE of 0.001 (call this label "1"). For some sentence-region-value triples, I cannot find a close enough statistical region to match (i.e. the MAPE is higher than a threshold I set, let's say 10%, which means I give it label "0"). 

This means that I can generate labels and training data for each sentence. Then I can train a classifier that looks at features of a sentence e.g. bag of words `[The, LOCATION_SLOT, in, 1600, had, NUMBER_SLOT,;, in, 1650, NUMBER_SLOT]` to predict 0 or 1 for any new sentence I come across. This is a proxy way of me being able to identify if any new sentence is a verifiable in Freebase or not, i.e. is a claim or not.

I hope this makes sense? Given you know what I am trying to do, can you see why having `["The LOCATION_SLOT LOCATION_SLOT in 1600 had NUMBER_SLOT NUMBER_SLOT ; in 1650 , NUMBER_SLOT NUMBER_SLOT ."]` as my parsed sentence from which to get my bag of words may conflict the classifier, as I have `[The, LOCATION_SLOT,  LOCATION_SLOT, in, 1600, had, NUMBER_SLOT,NUMBER_SLOT,;, in, 1650, NUMBER_SLOT,NUMBER_SLOT]`?

Given also as you say that each sentence should only have one location slot and one number slot, why are there multiple `tokenIDs2number` and `tokenIDs2location` generated from your `getNumbers` and `getLocations` functions? Which later steps get these down to only 1 slot each?

**Comment by dhruvghulati-zz** [comment]
Perhaps also I am overcomplicating, and using `"LOCATION_SLOT~-nn+\u00e3~-prep_such_as+countries~-dobj+*extend*LOCATION~nn+includes~-rcmod+MONEY~dep+in~dep+in~prep_to+NUMBER_SLOT"` (the sentences in `mainMatrix.json` you produce) as the input to my bag of words model (to start my pipeline) has the same effect of using the sentence format I have above? Or will I lose some information by doing so.

**Comment by andreasvlachos** [comment]
Answering the last question first: using the lexicalized dependency paths that I extract (such as the `LOCATION_SLOT...NUMBER_SLOT`) would loose information, and precisely the kind of information we want to add, e.g. the "muslim population" error we discussed in the skype call.

**Comment by andreasvlachos** [comment]
To the first question: I think I understand what you are trying to do, but I really think what my code returns is what you need. Let's stick with a binary classification formulation, i.e. 0/1 labels for simplicity (adding the costs later is easy, and extending it to multiclass is straightforward too). The instances you are labelling are sentences with a mention of a number and a mention of a location. Sentences can and will have more location and number mentions, but each **instance** for your classifier has a sentence with A location and a number mention specified. If not, then what would be the correct label for a sentence such as "The population of Greece is 11 million and its unemployment 27%"? You need to create two instances, one for each number mentioned. Does this make sense?

**Comment by dhruvghulati-zz** [comment]
I think I am doing the right thing in that case! In your exact example, I **am** creating two instances luckily - `<Greece, 11000000>` and `<Greece, 0.27>` or whatever the Freebase format is. I am also not doing the following filtering you did in `matrixFiltering.py` (but am accounting for aliases) - reason being to create as many training instances as possible for the classifier: 
- removes locations that have less than one value for a pattern
- removes patterns for which location lists are all over the place (high stdev)
- removes patterns that have fewer than arg1 location

And good news then on my sentence method, as I keep all the information like you say.
