### ISSUE TITLE
Is this a prediction of purely the value given the pattern and region? This is not a prediction of EV pair?

### ISSUE THREAD

**Issue by dhruvghulati-zz** [uclmr/simpleNumericalFactChecker#5]
This [line](https://github.com/uclmr/simpleNumericalFactChecker/blob/9e75b20045043936cc7cd201687f496a922582a3/src/main/baselinePredictor.py#L68) seems to only predict a value, or will it allow me to obtain the predicted EV pairs per pattern? Are we predicting both region, value for a pattern, or just a value, given a pattern and region? 

In general, what are the inputs and what are the outputs in terms of prediction? Are you stripping the actual property, region, value out and just look at what is in between e.g. “The _ of _ is _”, then predict all 3 values based on just knowing the sentence pattern? Or are you predicting value, given you know the property, region from what you observe from the slots? What did you use to make his entity, value pair prediction for a particular property essentially with regards to the code?

**Comment by andreasvlachos** [comment]
Not sure what you mean; the predict function is defined [here](https://github.com/uclmr/simpleNumericalFactChecker/blob/9e75b20045043936cc7cd201687f496a922582a3/src/main/baselinePredictor.py#L16-L34). It takes as arguments a region, e.g. "Spain" and a property, e.g. "population". To do so it uses the the text patterns selected during training. The entity value pairs from a particular pattern can be obtained from the textMatrix, as it is done during [training](https://github.com/uclmr/simpleNumericalFactChecker/blob/9e75b20045043936cc7cd201687f496a922582a3/src/main/baselinePredictor.py#L36).

**Comment by dhruvghulati-zz** [comment]
Thank you, makes more sense. Appreciate the guidance Andreas!
