### ISSUE TITLE
Linkage between KB values and actual EV pairs found in HTML JSONs and where in code found

### ISSUE THREAD

**Issue by dhruvghulati-zz** [uclmr/simpleNumericalFactChecker#6]
Actual Property, Region, Value triple: Is this obtained from the knowledge base for that sentence, or from the stored values we stripped out of the sentence (region, value, property)? 

If from the KB (the former), am I correct in saying we knew we obtained the sentence via a specific Bing web search of “Population, Germany” and so can query the knowledge base for those two property, region to obtain the third thing, the value?

**Comment by andreasvlachos** [comment]
Not sure I understand. All property, region, value triples are obtained from the KB by querying the knowledge base as per the first 3 pre-processing steps in the README.

All pattern, region, value triples are obtained by querying the web with bing for documents containing keywords about each property-region tuple, pre-processing them and extracting pattern, region, value triples, as per the remaining pre-processing steps and the matrix building/filtering scripts.

The baseline predictor all it does is to identify which patterns correlate well with each property.
